### ISSUE TITLE
ESTABLECER LA RED LOCAL

### ISSUE THREAD

**Issue by DiegoCaruanaMontes** [RoboRescueUMA/RR_Tools#3]

**Comment by MiguelIIan** [comment]
### Creado filtro MAC en el router
He configurado el router para que solo se puedan conectar los ordenadores del roborescue. Para ello he entrado en la ventana de administrador del router, he entrado en la opción "inalámbrico" y en la ventana "filtro MAC". Ahí he añadido uno a uno las direcciones MACs de cada una de las máquinas del taller del Roborescue.
Los ordenadores añadidos son: las dos torres, D27IIS1 y D27IIS2, los portatiles de Juanma y Antonio y los NUCs de Donatello y Horu.
