### ISSUE TITLE
Fijar las direcciones IP de los ordenadores del taller y volver a hacer el filtro MAC del router en la banda de 2.4GHz

### ISSUE THREAD

**Issue by MiguelIIan** [RoboRescueUMA/RR_Tools#4]
Hay que fijar las direcciones IP para poder conocerlas sin tener que verlas con el comando "ifconfig" cada vez que se encienda un ordenador. Esto nos sirve para poder controlar a los robots desde el ordenador sin tener que meterle una pantalla cada vez que se enciendan.

**Comment by ajmunoz00** [comment]
Eso como comenté no es operativo cuando el robot está lejos del router, propuse utilizar el nombre de la máquina como sustituto, ya que los routers o al menos la mayoría los registran y asocian la ip por defecto.  El plan es ver si en ROS es factible.

**Comment by MiguelIIan** [comment]
Si pero luego hablamos de que fijando las IPs podemos generar "alias" en los terminales de ubuntu con los que se simplifica y facilita mucho el uso

**Comment by MiguelIIan** [comment]
I have configured the MAC Filter for the 2.4 GHz band and I've also added the two laptops on both bands.

The process is simple. (Be careful to first add the MAC address from the computer you are working on, because you may lose the router control):

First you have to enter the router configuration window by typing on the web browser the router IP address.

1.- Select the "Wireless" advance configuration option

2.- Enter the "Wireless MAC Filter" tab

![ConfigRouter](https://github.com/user-attachments/assets/74760387-54ca-454b-bdbc-8b331a4a305e)

3.- Type the computer's MAC address you want to be in the network

4.- Click the plus button to add

![FiltroMac](https://github.com/user-attachments/assets/27f6827a-11fa-4f5b-8958-e7731eec341f)

Lastly, apply the changes and everything should be seted up.
